"""database creation

Revision ID: 612488b335e7
Revises: 48789b3e0e1a
Create Date: 2024-02-21 11:58:01.079359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612488b335e7'
down_revision = '48789b3e0e1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
