"""Renaming students to scholars

Revision ID: dc1de34fd507
Revises: f4381e9ae819
Create Date: 2024-02-21 12:02:41.275862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1de34fd507'
down_revision = 'f4381e9ae819'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('scholars', 'students' )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('students', 'scholars')